wandb_version: 1

_content:
  desc: null
  value:
    hyperparameters: '{''batch_size'': 1000, ''lr'': 0.01, ''epochs'': 5}'
_flags_cache:
  desc: null
  value:
    struct: null
_metadata:
  desc: null
  value: ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True,
    key=None, flags={}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>,
    {}), key_type=typing.Any, element_type=typing.Any)
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1673278733.838212
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.10.8
      5: 0.13.7
      8:
      - 3
      - 5
